# Generated by Django 6.0.2 on 2026-02-20 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("donations", "0001_initial"),
        ("donors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationhistory",
            name="donor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donation_history",
                to="donors.donor",
            ),
        ),
        migrations.AddField(
            model_name="donationhistory",
            name="slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donations",
                to="donations.donationslot",
            ),
        ),
    ]
