# Generated by Django 6.0.2 on 2026-02-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BloodInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("whole", "Whole Blood"),
                            ("rbc", "Red Blood Cells"),
                            ("plasma", "Plasma"),
                            ("platelets", "Platelets"),
                        ],
                        default="whole",
                        max_length=20,
                    ),
                ),
                ("quantity_units", models.PositiveIntegerField(default=0)),
                ("collection_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Blood Inventory",
            },
        ),
    ]
