# Generated by Django 6.0.2 on 2026-03-06 07:57

from django.db import migrations
from django.utils import timezone


def mark_expired_unavailable(apps, schema_editor):
    BloodInventory = apps.get_model("inventory", "BloodInventory")
    today = timezone.now().date()
    updated = BloodInventory.objects.filter(
        expiry_date__lt=today,
        is_available=True
    ).update(is_available=False)
    print(f"  Marked {updated} expired blood unit(s) as unavailable.")


def reverse_mark_expired(apps, schema_editor):
    # Non-destructive reverse: leave records as-is
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(mark_expired_unavailable, reverse_mark_expired),
    ]
