# Generated by Django 6.0.2 on 2026-02-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FraudLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flag_type",
                    models.CharField(
                        choices=[
                            ("duplicate_email", "Duplicate Email"),
                            ("duplicate_phone", "Duplicate Phone"),
                            ("fuzzy_name_match", "Fuzzy Name Match"),
                            ("donation_frequency", "Donation Frequency Exceeded"),
                            ("multiple_requests_ip", "Multiple Requests from Same IP"),
                            ("suspicious_pattern", "Suspicious Pattern"),
                            ("ml_anomaly", "ML Anomaly Detected"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Risk score 0–100"
                    ),
                ),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
