# Generated by Django 6.0.2 on 2026-02-20 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("user_approved", "User Approved"),
                            ("user_blocked", "User Blocked"),
                            ("user_unblocked", "User Unblocked"),
                            ("hospital_created", "Hospital Created"),
                            ("hospital_updated", "Hospital Updated"),
                            ("hospital_verified", "Hospital Verified"),
                            ("hospital_rejected", "Hospital Rejected"),
                            ("inventory_added", "Inventory Added"),
                            ("inventory_updated", "Inventory Updated"),
                            ("donation_approved", "Donation Approved"),
                            ("donation_rejected", "Donation Rejected"),
                            ("donation_completed", "Donation Completed"),
                            ("request_created", "Request Created"),
                            ("request_approved", "Request Approved"),
                            ("request_rejected", "Request Rejected"),
                            ("request_fulfilled", "Request Fulfilled"),
                            ("fraud_resolved", "Fraud Flag Resolved"),
                            ("slot_created", "Donation Slot Created"),
                            ("slot_updated", "Donation Slot Updated"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        help_text="e.g. User, Donor, BloodRequest", max_length=50
                    ),
                ),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                ("details", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
